#!/bin/sh

print_error() {
    echo "Error: $2" >&2
    exit "$1"
}

editor_path="$(realpath "$(dirname "$0")")"

case "$1" in
    start) docker run --rm --name server -d -p 8082:80 --mount type=bind,source="$editor_path/",target=/var/www/html php:apache ;;
    stop) docker stop server ;;
    *) print_error 1 "Wrong argument given. Possible arguments: 'start', 'stop'"
esac